spring:
  application:
    name: enrollment-service

enrollment-service:
  enrollment-controller-base-url: /v1/api/enrollments/user
  internal-controller-base-url: /v1/api/enrollments/internal
  admin-controller-base-url: /v1/api/enrollments/admin

jwt:
  user-secret-key: ${JWT_USER_SECRET_KEY}
  internal-secret-key: ${JWT_INTERNAL_SECRET_KEY}

server:
  port: 8084
