spring:

  config:
    activate:
      on-profile: dev


  datasource:
    url: jdbc:postgresql://localhost:5434/ch_enrs_dev_db
    username: ch_enrs_dev_user
    password: dbhunter_dev
    driver-class-name: org.postgresql.Driver


enrollment-service:
  client:
    course-service:
      host: http://localhost:8082
      internal-controller-url: /v1/api/courses/internal
    payment-service:
      host: http://localhost:8086
      internal-controller-url: /v1/api/payments/internal