spring:

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:postgresql://enrollment_service_postgres_prod:5432/ch_enrs_prod_db
    username: ch_enrs_prod_user
    password: dbhunter_prod
    driver-class-name: org.postgresql.Driver

enrollment-service:
  client:
    course-service:
      host: course-ms:8082
      internal-controller-url: /v1/api/users/internal
    payment-service:
      host: payment-ms:8086
      internal-controller-url: /v1/api/payments/internal