spring:
  application:
    name: enrollment-service


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

enrollment-service:
  enrollment-controller-base-url: /v1/api/enrollments/user
  internal-controller-base-url: /v1/api/enrollments/internal

jwt:
  user-secret-key: ${JWT_USER_SECRET_KEY}
  internal-secret-key: ${JWT_INTERNAL_SECRET_KEY}

server:
  port: 8084
