spring:
  application:
    name: payment-service


jwt:
  user-secret-key: ${JWT_USER_SECRET_KEY}
  internal-secret-key: ${JWT_INTERNAL_SECRET_KEY}

server:
  port: 8086


payment-service:
  internal-controller-url: /v1/api/payments/internal