spring:

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://course_service_postgres_prod:5432/ch_cs_prod_db
    username: ch_cs_prod_user
    password: dbhunter_prod
    driver-class-name: org.postgresql.Driver

redis:
  server:
    url: redis://coursehub-redis:6379

kafka:
  bootstrap-servers: coursehub-kafka:9092

course-service:
  client:
    identity-service:
      host: identity-ms:8081
      internal-controller-url: /v1/api/users/internal