spring:
  application:
    name: course-service

course-service:
  public-base-url: /v1/api/courses/public
  admin-base-url: /v1/api/courses/admin
  internal-base-url: /v1/api/courses/internal
  creator-base-url: /v1/api/courses/creator
  categories-base-url: /v1/api/courses/categories

server:
  port: 8082

jwt:
  user-secret-key: ${JWT_USER_SECRET_KEY}
  internal-secret-key: ${JWT_INTERNAL_SECRET_KEY}


courses:
  popular:
    min-rating: 4.0
  recent:
    days: 10