spring:

  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB


minio:
  user-profile-photo-bucket: user-profile-pictures
  course-profile-photo-bucket: course-thumbnails
  video-profile-photo-bucket: video-thumbnails
  course-videos-bucket: course-videos
  url: http://coursehub-minio:9000
  access-key: root_user
  secret-key: root_pass


media-stock-service:
  client:
    course-service:
      host: http://course-ms:8082
      internal-controller-url: /v1/api/courses/internal
    enrollment-service:
      host: http://enrollment-ms:8084
      internal-controller-url: /v1/api/enrollments/internal

redis:
  server:
    url: redis://coursehub-redis:6379

kafka:
  bootstrap-servers: coursehub-kafka:9092