spring:
  application:
    name: media-stock-service

jwt:
  user-secret-key: ${JWT_USER_SECRET_KEY}
  internal-secret-key: ${JWT_INTERNAL_SECRET_KEY}

server:
  port: 8083

media-stock-service:
  video-base-url: /v1/api/media/video
  photo-base-url: /v1/api/media/photo
